### ISSUE TITLE
ERROR 404: Not Found

### ISSUE THREAD

**Issue by damir206** [MicrosoftDocs/mslearn-distribute-load-with-traffic-manager#5]
https://raw.githubusercontent.com/MicrosoftDocs/mslearn-distribute-load-with-traffic-manager/master/azuredeploy.json is failing when executed from exercise at https://docs.microsoft.com/en-us/learn/modules/distribute-load-with-traffic-manager/3-exercise-priority-routing

--2019-12-30 16:28:08--  https://raw.githubusercontent.com/MicrosoftDocs/mslearn-distribute-load-with-traffic-manager/module-update/index.eastasia.html
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:443... connected.
HTTP request sent, awaiting response... 404Not Found
2019-12-30 16:28:08 ERROR 404: Not Found.

Looks like sub-folder "module-update" should be replaced with "master"

**Comment by phhlho** [comment]
There is currently a pull request with the fix for this issue outstanding [PR#3](https://github.com/MicrosoftDocs/mslearn-distribute-load-with-traffic-manager/pull/3). In case someone else stumbles on this issue before it's merged in, I've forked the code and made the change. You can run the command from the exercise and aim it at my fork:
` az group deployment create     --resource-group learn-57aa8379-db66-4216-803f-f03630e0dcda     --template-uri  https://raw.githubusercontent.com/phhlho/mslearn-distribute-load-with-traffic-manager/master/azuredeploy.json     --parameters password="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)"`

**Comment by damir206** [comment]
@phhlho Thank you, it works now.

**Comment by jboeshart** [comment]
Fixed in #3, thanks for the heads up on this issue, sorry for the delay in getting this resolved.
